### ISSUE TITLE
Yt-dlp patched 

### ISSUE THREAD

**Issue by trimechee** [kannagi0303/yt-dlp-gui#14]
Hello, Thank you very much for this awesome great donwloader !

i have suggestion please :  i find YTDL-patched =yt-dlp fork with some more features : keep merging with yt-dlp/yt-dlp
implement miscellaneous extractors as possible
make -U work (yes, really works)
do anything best, may be it will be good to add this downloader  ! thank you .

https://github.com/ytdl-patched/ytdl-patched

**Comment by kannagi0303** [comment]
Thank you so much for your valuable advice.
I have a little look at the project you have provided.
I will try to make the GUI more flexible to use it.
You specifically mentioned the -U parameter, I prefer to use the menu to let the user update it manually.
If you have other ideas let me know and I will implement them as soon as possible :)

**Comment by trimechee** [comment]
it's awesome sensational! 🥇  it's already huge the number of videos and sites that our beloved Yt-dlp-gui allows you to download and we thank you very much for your great kindness and help and generosity and huge efforts to make this magnificent software :) 💯 

I have a suggestion please, it seems there are a lot of software named "Yt-dlp-gui" which can cause confusion, so maybe it will be great to distinguish itself from other software and be easily recognizable to change the name of your wonderful software!

**Comment by trimechee** [comment]
Other sugeestion please : we hope that it will be a web browser extension invented or recommended by our -beloved  Yt-dlp-gui  will be added and be compatible with  Yt-dlp-gui  and detected links in web browser  will be send directly to Yt-dlp-gui so this extension will be a verified trusted extension inspected and tested by our beloved amazing Media-Downlader and there, we will be able to detect and capture some complicated embeded hided streams streams from the web browser and we would no longer need to use some suspect extensions that could inject malware or ads !


i find  some open source extensions that  could help to make web browser extensionto  download embeded hided content videos !

https://github.com/rowrawer/stream-detector

https://github.com/chandler-stimson/live-stream-downloader

https://github.com/zaidka/cliget

https://github.com/globocom/m3u8

https://github.com/HeiSir2014/M3U8-Downloader

https://github.com/hestyle/m3u8_downloader

https://github.com/kz26/gohls

https://github.com/Last-Order/Minyami

https://github.com/Momo707577045/m3u8-downloader

https://github.com/Momo707577045/media-source-extract

https://github.com/nilaoda/N_m3u8DL-RE

https://github.com/puemos/hls-downloader

https://github.com/Spark-NF/hls-downloader

https://chrome.google.com/webstore/detail/m3u8-finder-and-hls-playe/gijhpnmjcpbddpedmmdihijogkkejfgj?hl=en

https://www.hlsloader.com/

https://github.com/nilaoda/N_m3u8DL-CLI

**Comment by kannagi0303** [comment]
Thanks for your information.

The main appeal of yt-dlp-gui is to make people use the powerful tool yt-dlp better. (That's why the named yt-dlp-gui)
So there are no plans to make a browser extension.
I can use yt-dlp-gui with clipboard to make the process smoother, or there are other open source projects willing to cooperate.
As it stands, this feature will not be added to this project (maybe in other projects later)
hope you understand.

**Comment by trimechee** [comment]
The description of Yt-dlp-gui said "Features
Easy-to-use
Portable", 

but i see " .exe" version in releases page , so wich version we shoud download ? we hope that there is executable version, that make integration withs wndows 10 more easy i think, and it would be more earsy for newbies and beginers if Yt-dlp-gui donwload and install automatically ffmpeg and yt-dlp and update them automatically, thank you !


 I wonder if we should use the classic FFmpeg or the special version of FFmpeg to avoid bugs? because there is a special builds of FFmpeg for yt-dlp to fix some bugs, it will be great if YouTua can add ann update automatically this special builds of FFmpeg to fix some bugs for example

[Fix AAC HLS streams being truncated mid stream]

[Fix for YouTube's VP9 encodes with non-monotonous DTS]

https://github.com/yt-dlp/FFmpeg-Builds

and which version of ffmpeg we whoud downllod please ? there is two version : I decided to donwload this ffmpeg special build, there is 2 versions for windows, ffmpeg-master-latest-win64-gpl-shared.zip 44 mb and ffmpeg-master-latest-win64-gpl.zip 144mb, which one we should download and install please ? and is it really necessary to download and instal also ffprobe please ?

https://github.com/yt-dlp/FFmpeg-Builds/releases



and should we install the latest version of NET Framework 4.7.2 or 4.8 ?

**Comment by kannagi0303** [comment]
> i made this suggestion about extension just because there is some embeded videos in streaming web sites and yt-dlp can't detect them

I personally use [Stream Recorder - download HLS as MP4](https://chrome.google.com/webstore/detail/stream-recorder-download/iogidnfllpdhagebkblkgbfijkbkjdmm)
it works fine.
Regarding the streaming media, it may be nested or contain encryption, I don't think it can be downloaded through tools like yt-dlp just by detecting the streaming media.
Making a browser that intercepts streaming may be the ultimate solution.

**Comment by kannagi0303** [comment]
> but i see " .exe" version in releases page , so wich version we shoud download ? we hope that there is executable version, that make integration withs wndows 10 more easy i think, and it would be more earsy for newbies and beginers if Yt-dlp-gui donwload and install automatically ffmpeg and yt-dlp and update them automatically, thank you !

Yes, I have considered the automatic download feature.
Just like you hesitating which version, I have to find the most common version, which needs more suggestions from users.

About FFMPEG:
Since this is just a GUI. Any version of FFMPEG can be to use.
FFMPEG is mainly used in two situations, the first is to record Live streams, and the second is to encapsulate video and audio into containers (.mp4, .webm...)
For version differences, please refer to https://github.com/BtbN/FFmpeg-Builds/blob/master/README.md

I am using .NET 6 to develop.
But in order to avoid dependency problems.
I have packaged all needed items in a single file `yt-dlp-gui.exe`.
In theory there is no need to install any framework.
Although the cost is a huge executable file.
Even so, I can't guarantee that everyone can use it,
Please let me know if you run into problems

**Comment by trimechee** [comment]
Yes of course !  thank you so much for these precious informations :)
