### ISSUE TITLE
New engine : Lux, you-get, wget and aria2, and  N_m3u8DL-CLI

### ISSUE THREAD

**Issue by trimechee** [kannagi0303/yt-dlp-gui#15]
Hello, thank you very much fot this awesome and fantastic amzing downloader 🥇 💯 !

i have suggestion please : it will be even more great if there is integration with ths famous CLI software because yt-dlp may suffer from censorship like youtube-dl on github when youtube- dl was removed from github after a dmca complaint.....

You-Get
Dumb downloader that scrapes the web

You-Getis a tiny command-line utility to download media contents (videos, audios, images) from the Web, in case there is no other handy way to do it.

https://github.com/soimort/you-get

Lux is a fast and simple video downloader built with Go

Fast and simple video download library and CLI tool written in Go

https://github.com/iawia002/lux

N_m3u8DL-CLI to dowload m3u8 streams 

https://github.com/nilaoda/N_m3u8DL-CLI

 aria2c is used primarily to download regular large files from the internet.

https://aria2.github.io/

 wget download regular large files from the internet.

https://www.gnu.org/software/wget/

**Comment by kannagi0303** [comment]
Thanks for your compliment. :)

Making it simple, convenient, and practical is an indicator.
So any suggestions and recommendations are welcome.
The current version already supports the use of aria2. 
As for other projects, I don't know how to use it and its features.
I will actively integrate if it works. :)

**Comment by trimechee** [comment]
Great ! thank you very much !!

i find also an amazing CLI command line software to donwload m3u8 streams N_m3u8DL-CLI , i  know it is very difficult and complicated to integrate these all new comand line softwares  and it is suggestion and thak you again to offer us this amzign  downloader, and  yt-dlp ia already enogh strong to download video from many and many websites :)

https://github.com/nilaoda/N_m3u8DL-CLI

**Comment by kannagi0303** [comment]
Thank you for your expectations and suggestions
For now, yt-dlp-gui is to make people use the powerful tool yt-dlp better.
To make perfect use of yt-dlp, There's still a long way.
It is quite difficult to be a downloader that can download all videos.
In contrast, making GUI for good software will be simpler.
If have a chance, Does not exclude making GUI for other software

**Comment by trimechee** [comment]
Yes, you have right 💯 👍  and it  will be great to add other software if needed some days , thank you so much :)
