### ISSUE TITLE
Entire or part of the video

### ISSUE THREAD

**Issue by trimechee** [kannagi0303/yt-dlp-gui#16]
Hello, in the chagelog of yt-dlp, that said " Don't download entire video when no matching --download-sections", so can we donwload only determinated part of video please ? beacause sometimes, we may find a very long video of a tv show that lasts 3 hours or 4 hours and we would just like to download only the part of the video that interests us to save data, can there be an option to download only a specific part of the long video please ?

https://www.videohelp.com/software/yt-dlp/version-history

**Comment by kannagi0303** [comment]
Please refer to [yt-dlp README](https://github.com/yt-dlp/yt-dlp#download-options).
`--download-sections REGEX` Parameter Description.

Regarding this kind of question, it is recommended that you ask the author directly, there is a larger traffic and community there, and I believe you can get a more detailed answer

**Comment by trimechee** [comment]
Yes, but i don't konow how to use command line, my request is can you please add option to speicfy the time i mean  the start and the end of the specefic part of the video that we would to donwload just a part and not entirely ??

**Comment by kannagi0303** [comment]
There is already the feature that contains what you need.
Just switch to the `Advance` tab and enter the desired time period.

**Comment by trimechee** [comment]
Great awesome  !! thank you very much !! 💯

**Comment by trimechee** [comment]
and please is there option "sponsor block" to block promotion ads in youtube video ?

**Comment by kannagi0303** [comment]
First of all, I hope you can correctly recognize the characteristics of each project.
After all, my project is based on the yt-dlp project to enhance its user experience, and I cannot subvert the non-existent functions.
I know you have many of the same requests from multiple authors on similar projects. 
If you still can't find the right software for you. 
Maybe you can invest in development like me and make software that makes you happy.
In view of my original intention, I still hope to help users like me who cannot be satisfied by other projects.
I will try my best to help with any issues within the scope of this project.
So please be more respectful and kind to every author who seriously replies to you.

**Comment by trimechee** [comment]
I don't understand your rude and ungrateful attitude, I already praised you a lot, and I politely ask you because you yourself asked me to give you suggestions to improve your software, " I know you have many of the same requests from multiple authors on similar projects?" you are spying on me ? it's not surprising because you live in china which spies on everyone, and while I make requests for other projects, I don't hide it and it's a source of pride and the developers are happy that I report bugs and suggestions , no software is perfect and I do the favor of testing, I made several suggestions to other developers and they answer me politely, what's your problem if I talk to other developers?!! you are jealous ? you think you're the best developer and I have to use only your software?!! my suggestions and bug reports help improve the software for a better experience for everyone, really you're rude and I don't understand your attitude, I'm not a developer, I don't know anything about IT, I can't not even use a command line, come on I withdraw my compliments on your software, there are many who are better on your software, I am doing you a favor by trying to make you improve your software, you are the bad guy, my suggestions are the huge research fruit, i suggested you to use you get and lux and you closed the ussue, that's rude when you haven't finished doing them, i have make requests and some developers do not arrive, what is your problem that I make suggestions to other developers? I'm happy not to have tested your software, I even suggested your software to a famous site to advertise you, I propose to sponsor the projects, really you are ungrateful, if you close the ssues while you don't fix the problems, you might as well not develop, you're bad polo, don't try this software, there are others like media downloader, really you're stupid, I have a twitter account with a lot of subscribers, I could advertise you, encourage people to donate to you, I did you a favor, you're anonymous, we don't know your name or your first name, we're doing you a huge favor for taking the risk to test your software when you are anonymous and you live in a country that spies on everyone, kannagi0303 you are ungrateful, it is a huge risk to test your software, in addition you are spying on me, it scares me, continue close the issues and we'll see if you're going to improve your software, plus you're rude, you say "give me some suggestions, qua nd we do it to you, you insult people, really you are rude contradictory

**Comment by trimechee** [comment]
apparently you're blind, I kept thanking you, putting you emoticon gold medal and 100%, my messages are full of "thank you so much", your project is "awesome and fantastic" and c it's you yourself who asks me to make suggestions, I'm wasting my time with you, it takes effort to make suggestions, find ideas to improve your software...too bad for you and change glasses because apparently you you are blind and above all an ungrateful spy, no wonder you live in China which oppresses the Ouighurs reduced to slavery by china

**Comment by trimechee** [comment]
apparently you're blind, I kept thanking you many times, putting you emoticon gold medal and 100%, my messages are full of "thank you so much", your project is "awesome and fantastic" and c it's you yourself who asks me to make suggestions, I'm wasting my time with you, it takes effort to make suggestions, find ideas to improve your software...too bad for you and change glasses because apparently you you are blind and above all an ungrateful spy, no wonder you live in China which oppresses the Uighurs reduced to slavery by China, and yes, i made other request to other devlopers, youare not the only brillant developer in the universe, i and i ahve user many downloader in the same computers bacause each downlaoder have its specificity and unique features, and you have close issues sections whereas you didn't don what we have suggested like lux and you get, this is malpolite, i d'ont care about your dowloader, i have other great downloader with developer more polite than you , i made you favor to make you some suggestion beacause you have me  have pity on you beacause you said to me to do suggestions to you lol, don't talk me again , i don't care about you

**Comment by trimechee** [comment]
you have to prove to me that you deserve that I take the risk of installing your software while you are anonymous from china , why are you hiding your identity? you have no website, no bio, no personal info, it's risky to use your software, that's why I make suggestions and ask so that you deserve that I install your software, and I see that you don't deserve that I Trust me, do you have anything better in your life than spying on me when I talk to other developers? try to ask your government not to massacre the Uyghurs anymore, it's better, sahme on you spy

**Comment by kannagi0303** [comment]
First of all, I have explained to you many times, I just provide a GUI, so that people can easily use the CLI, as for your requirements, I will try my best to satisfy you and answer you within the scope of what I can provide.

As for github, anyone can view everyone's inquiries and journeys, which is a useful feature that allows people to better understand how to help you.

Basically my project has basically no visitors for the first 5 months because it's just code that I store for myself. I've never marketed my own work, so users are free to rate it, use it or not.

Because of the tools you mentioned, I did not deny your information, but I read the information in detail for each item, and I answered you politely. If applicable, I will actively use it, but the actual situation As far as I'm concerned, those are already to the extent that you need to develop a GUI separately, and I will answer you politely. I believe most of the developers you meet have similar answers, right?

**Comment by kannagi0303** [comment]
As for all the accusations you mentioned, I'll keep it, I'll respect your freedom of speech because I'm from a free and peaceful country, you can love or hate anyone, and I don't like many things about that place .
