### ISSUE TITLE
cannot merge subtitle and video with gui

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#17]
gui does not support subtitle and video merge?

subtitle file stays as seperate file.

**Comment by kannagi0303** [comment]
Yes, not yet supported.

**Comment by bachig26** [comment]
> Yes, not yet supported.

will it be supported in coming releases?

**Comment by kannagi0303** [comment]
I tested it with yt-dlp. Sometimes there are some problems with embedded subtitles. I can try to wrap it with ffmpeg. If it goes well, I can add this feature in the recent update. :)

**Comment by kannagi0303** [comment]
Release new version, now it is possible to merge subtitles, please enable it in `Advance` tab

**Comment by bachig26** [comment]
closing this issue as done due to the commit https://github.com/kannagi0303/yt-dlp-gui/commit/2160f39774402a83a353b56fb0b2f247481e2ef1.

if there is some issue that I found during my use, I'll open it again or a new issue.
