### ISSUE TITLE
output folder option is not available

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#19]
from yaml file:
`# Last Browsed Folder`
`TargetPath: C:\yt-dlp\`

it is like this for me, I changed this to like `TargetPath: E:\yt-dlp\` to set the output location for the downloaded files, but it get's reset after the new session of the gui.

**I hope there is an option to define the output location.**

**Comment by kannagi0303** [comment]
You can use `Browse` Button directly to switch your storage location.
When there is no video, a dialog box for selecting a folder will pop up.
When there is a video, a dialog box for selecting a file to save will pop up.

If you want to modify the yaml file directly, please close `yt-dlp-gui.exe` first.
It only reads the settings into memory at startup, and writes the settings back when the settings are changed.

**Comment by bachig26** [comment]
closing as the result of the possible use of `Browse` Button.
