### ISSUE TITLE
cookie functionality? new option `Ask`

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#21]
i want to ask if there is possibility to add an `Ask` option to Cookie function, like manually allowing the cookie instead of other options.

**the `When needed` option feels like `Always` function with on request capability**, but I would like this to have an fully manual option.

**Comment by kannagi0303** [comment]
Yes, I can add this option and I will schedule the implementation

**Comment by kannagi0303** [comment]
The new version `2022-10-10` is released, although I added the option, but I have not tested this function in detail
