### ISSUE TITLE
A new option like `Always on Top` with user definable _shortcut key_ functionality.

### ISSUE THREAD

**Issue by kannagi0303** [kannagi0303/yt-dlp-gui#23]
A new option like `Always on Top` with user definable _shortcut key_ functionality.

_Originally posted by @bachig26 in https://github.com/kannagi0303/yt-dlp-gui/discussions/13#discussioncomment-3804481_

**Comment by kannagi0303** [comment]
Regarding this, there are actually two functions.
1. I can add settings about `Always on Top`, or move the window to the foreground under certain conditions
2. Using the `global shortcut key` must call the operating system to register related programs, most of which I am not inclined to this aspect of the design. Still, I'll try to implement this feature and add it if it doesn't cause problems.

**Comment by kannagi0303** [comment]
The new version `2022-10-10` is released, you can set `Always on Top`.
Since I don't limit the number of executable entities, `Shortcut Key` is likely to cause confusion, so let's not implement it for now

**Comment by bachig26** [comment]
I'm closing this issue as a result of the commit 78cb16be6dbd6e2c639f165a5d2db31ac7271aa3.

Will reopen if needed.
