### ISSUE TITLE
set temp folder as target folder or an option to set it

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#27]
currently, the temp folder (that is the temporary location where the video, audio and subtitle file download before going to output location) is defaulted to gui location.

it would be great to have it as the output or target location/folder, or have an option in the settings to set my user.

**Comment by kannagi0303** [comment]
I have not been able to implement this implementation in a short period of time, for the following reasons

* With the current working conditions, I can't find a better reason to add this option.
* For the foreseeable future features, I will use the temporary requirements, and I will not implement this implementation until the whole process is conceived

Sorry, I hope you can understand, this requirement should not be added in the recent update

**Comment by kannagi0303** [comment]
Hello, thank you for using my GUI. 

Sorry for the wait. 
I have released a new version which includes the ability to customize the temp folder.
If you are interested, please try the new version.
