### ISSUE TITLE
Add `Open Folder` option

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#29]
This is a request for adding the `Open Folder` option to **open the Output Folder directly from the GUI**.

**Comment by kannagi0303** [comment]
Before `Analyze` any URL, click `Browse`, I think this may be the function you said

**Comment by bachig26** [comment]
> Before `Analyze` any URL, click `Browse`, I think this may be the function you said

@kannagi0303 `Browse` button open as `Select Folder` or `Save As` in their respective situation, but my request is like an button `Open Folder` acts as hyperlink to the Output folder in File Explorer.

**Comment by kannagi0303** [comment]
Do you want to call the system's `File Explorer ("explorer.exe")` and browsing the output folder by clicking the GUI's `Button`?

I can implement this function in the next update (Hopefully I can find a good place to put the button :) )

**Comment by bachig26** [comment]
> Do you want to call the system's `File Explorer ("explorer.exe")` and browsing the output folder by clicking the GUI's `Button`?
> 
> I can implement this function in the next update (Hopefully I can find a good place to put the button :) )

yes, this was the one that I'm looking for. 👍

**Comment by kannagi0303** [comment]
The new version `2022-10-10` is released. Now you can achieve the function you want by adding a small button. When the target file does not exist yet, it will help you open the folder. If it exists, explorer will automatically place the cursor on the file
