### ISSUE TITLE
possibility to make the GUI Window size persistent as last session

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#31]

**Comment by kannagi0303** [comment]
It is theoretically possible to record and return the final size (or position)

(There is a small bug in the Microsoft development platform that may be encountered, I am not sure if I will encounter it, or if Microsoft has fixed it)

**Comment by bachig26** [comment]
> It is theoretically possible to record and return the final size (or position)
> 
> (There is a small bug in the Microsoft development platform that may be encountered, I am not sure if I will encounter it, or if Microsoft has fixed it)

yes, last session window size and position will be good to have.

if possibly you can implement this then i hope to see it.
thanks for the reply.

**Comment by kannagi0303** [comment]
The new version `2022-10-10` is released, I have added two settings to separate the position and size, but if the GUI runs out of your screen unfortunately, you can set the rememberwindowstate items of yaml to false , which will make the GUI open according to the default state
