### ISSUE TITLE
我的一个想法

### ISSUE THREAD

**Issue by SONGjiemo** [kannagi0303/yt-dlp-gui#37]
希望便携版本有一个bin目录里面直接放着yt-dlp.exe，ffmpeg.exe，aria2c.exe就可以。目前的单文件太大了，
我希望能单独GUI出来我想自己更新yt-dlp.exe文件

**Comment by kannagi0303** [comment]
目前为把所有依赖库都包含进去的执行文件，其中不包含yt-dlp.exe，ffmpeg.exe，aria2c.exe等文件，您必须自行复制文件到bin里，最低必要文件为yt-dlp.exe，ffmpeg.exe

**Comment by SONGjiemo** [comment]
> 
那我问一下，你这个下载器能不能支持 直接 下载m3u8文件。我很多时候把一下小众网址抓取了m3u8地址  在下载目前用的是别人写的批处理。我希望你这边直接支持。再就是  能不能给我一个中文版本的，现在是英文的

**Comment by SONGjiemo** [comment]
> 目前为把所有依赖库都包含进去的执行文件，其中不包含yt-dlp.exe，ffmpeg.exe，aria2c.exe等文件，您必须自行复制文件到bin里，最低必要文件为yt-dlp.exe，ffmpeg.exe


那我问一下，你这个下载器能不能支持 直接 下载m3u8文件。我很多时候把一下小众网址抓取了m3u8地址 在下载目前用的是别人写的批处理。我希望你这边直接支持。再就是 能不能给我一个中文版本的，现在是英文的

**Comment by kannagi0303** [comment]
感谢您的留言。

首先我想先向您说明，yt-dlp-gui并不是一个下载器，而是 命令列下载工具yt-dlp 的图形辅助界面。由于yt-dlp没有支持直接下载m3u8文件，所以您可能需要找寻其他更为适合您需求的下载器(或工具)。

至于多语言的支持(包含中文在内)，预计会在未来的版本中支持，不过没有详细的时间表，会视使用者的需求数来决定。

**Comment by SONGjiemo** [comment]
> 感谢您的留言。
> 
> 首先我想先向您说明，yt-dlp-gui并不是一个下载器，而是 命令列下载工具yt-dlp 的图形辅助界面。由于yt-dlp没有支持直接下载m3u8文件，所以您可能需要找寻其他更为适合您需求的下载器(或工具)。
> 
> 至于多语言的支持(包含中文在内)，预计会在未来的版本中支持，不过没有详细的时间表，会视使用者的需求数来决定。

他是支持的命令是：yt-dlp 地址
测试例子
yt-dlp https://json.bid/LOVE/BYG/dcd4600316e220a2277bf10b08dc8b85.m3u8

**Comment by SONGjiemo** [comment]
> 
请看这个结果
![image](https://user-images.githubusercontent.com/46627639/199464738-c811623e-f269-4adb-acfd-8df67c4680ba.png)

**Comment by kannagi0303** [comment]
是的，感谢您的回复。
首先为我的回复致歉，由于m3u8只是个播放清单文件，我不确定使用者是否会遇到加上各种保护措施的m3u8而导致yt-dlp无法解析下载，我无法斩钉截铁的说有支持，由于每位来询问的用户理解都不尽相同，也遇过些许不理智的用户，还请您这方面多多见谅多多包涵。

关于您提到要下载m3u8的部份。
目前预设GUI的操作逻辑，都是预先让使用者先进行解析(Analyze)，在取得资讯后再让使用者挑选格式(Formats)... 等项目，才开始进行下载。这个流程比较适用大多数网站。

由于无法从m3u8取得影片资讯，所以不适用这个流程。
为了符合您的需求。我列出一些方案与可行性。

* 增加一个按钮，弹窗后输入地址按确认后，直接进行下载 (实作较为简单单纯)
* 直接判别地址让使用者可以点选下载 (无法正确判断所有地址，要能正确的判断会有额外的延迟与频宽发生，实作麻烦)

不知您是否有其他方案能提供?

如果您对执行文件大小很在意的情况，我这边开发使用的工具与单一执行文件所需要的相依，再怎样压缩或缩减，也是需要70MB~80MB左右，除非微软能提供产出更小的开发工具。

**Comment by SONGjiemo** [comment]
> 是的，感谢您的回复。 首先为我的回复致歉，由于m3u8只是个播放清单文件，我不确定使用者是否会遇到加上各种保护措施的m3u8而导致yt-dlp无法解析下载，我无法斩钉截铁的说有支持，由于每位来询问的用户理解都不尽相同，也遇过些许不理智的用户，还请您这方面多多见谅多多包涵。
> 
> 关于您提到要下载m3u8的部份。 目前预设GUI的操作逻辑，都是预先让使用者先进行解析(Analyze)，在取得资讯后再让使用者挑选格式(Formats)... 等项目，才开始进行下载。这个流程比较适用大多数网站。
> 
> 由于无法从m3u8取得影片资讯，所以不适用这个流程。 为了符合您的需求。我列出一些方案与可行性。
> 
> * 增加一个按钮，弹窗后输入地址按确认后，直接进行下载 (实作较为简单单纯)
> * 直接判别地址让使用者可以点选下载 (无法正确判断所有地址，要能正确的判断会有额外的延迟与频宽发生，实作麻烦)
> 
> 不知您是否有其他方案能提供?
> 
> 如果您对执行文件大小很在意的情况，我这边开发使用的工具与单一执行文件所需要的相依，再怎样压缩或缩减，也是需要70MB~80MB左右，除非微软能提供产出更小的开发工具。

增加一个按钮、这个方案就可以了。我非常喜欢你的工具。希望尽快添加。再就是设置下载线程数设置
非常感谢

**Comment by kannagi0303** [comment]
您好

经过我后续的测试，让工具能顺利的取得视频地址的资讯。
我修改了可能会造成错误的代码，并且测试了在网上数个公开的m3u8地址，并且能顺利的下载。
不需增加按钮，只需按照原本的操作步骤应该就能顺利下载。

我发布了新的版本，然而我还是没有把握能适用到所有m3u8，如果您后续使用有遇到问题，还请您通知我。
感谢您喜欢使用我的工具，最初只是网上没适用自己的工具所以才开始自己制作的项目，
如果只是简单可以实现的功能与想法都可以提出来一起讨论。

**Comment by SONGjiemo** [comment]
> 您好
> 
> 经过我后续的测试，让工具能顺利的取得视频地址的资讯。 我修改了可能会造成错误的代码，并且测试了在网上数个公开的m3u8地址，并且能顺利的下载。 不需增加按钮，只需按照原本的操作步骤应该就能顺利下载。
> 
> 我发布了新的版本，然而我还是没有把握能适用到所有m3u8，如果您后续使用有遇到问题，还请您通知我。 感谢您喜欢使用我的工具，最初只是网上没适用自己的工具所以才开始自己制作的项目， 如果只是简单可以实现的功能与想法都可以提出来一起讨论。

好的、我测试一下。有问题我提出了。我有个疑问就是默认线程数是多少。我希望可以设置他 或者默认5个线程.这样就好了。

**Comment by kannagi0303** [comment]
关于线程数。
当在Options里面启用aria2c，并且目标地址能使用aria2c的情况下，GUI会在Downloader的地方显示为aria2c。
此时Connections即为连线数。

![sh](https://user-images.githubusercontent.com/78738403/199928108-aa55c95a-2fde-416c-a159-339027e6c1e6.jpg)

基本上aria2c会使用[预设的设置](https://aria2.github.io/manual/en/html/aria2c.html)，如果您想更改aria2c的参数，可以使用config功能，并添加参数，可参考如下

`--downloader-args aria2c:"-x 16 -k 10M"`

希望这回答对您有帮助。

**Comment by SONGjiemo** [comment]
> 关于线程数。 当在Options里面启用aria2c，并且目标地址能使用aria2c的情况下，GUI会在Downloader的地方显示为aria2c。 此时Connections即为连线数。
> 
> ![sh](https://user-images.githubusercontent.com/78738403/199928108-aa55c95a-2fde-416c-a159-339027e6c1e6.jpg)
> 
> 基本上aria2c会使用[预设的设置](https://aria2.github.io/manual/en/html/aria2c.html)，如果您想更改aria2c的参数，可以使用config功能，并添加参数，可参考如下
> 
> `--downloader-args aria2c:"-x 16 -k 10M"`
> 
> 希望这回答对您有帮助。

你好，我使用过程中有个新发现，就是可以下载剧集但是我不知道命令
你有时间可以研究一下。
![image](https://user-images.githubusercontent.com/46627639/200122535-2d796a9f-cff6-4e68-8f5c-4400519bb619.png)

**Comment by kannagi0303** [comment]
您好，關於下載`Playlist`的需求常被提出(#28)
yt-dlp 可以直接輸入list地址去下載整份相關視頻。
不過目前GUI無法提供該特性，主要跟初始概念不同，如要實現該功能，必須要重新設計UI。
如同在其他需求的issues當中皆回答著，這是一個未來預計實現的功能，並不會在短時間內被實作。
對未來列表下載有任何想法或建議可以在(討論版)[https://github.com/kannagi0303/yt-dlp-gui/discussions/13]裡面共同來討論。
如果您急需要有這項功能的GUI，我推薦搭配使用Github當中其他作者製作的GUI，大多數的工具都有提供下載整份Playlist的特性。
