### ISSUE TITLE
Great work! Can you add a CONVERT TO MP4 function?

### ISSUE THREAD

**Issue by lovaxi** [kannagi0303/yt-dlp-gui#4]
tks

**Comment by kannagi0303** [comment]
Thank you for your affirmation.
Short answer is : Yes, I can do it. And I positively want to integrate all the required functions.
Regarding the mentioned functions, I am not sure whether I can understand your needs further.

About mp4 :
* itself is a container
* When the selected format is video(mp4)+audio(m4a), you can get the mp4 file directly
* I can remuxing video+audio to mp4 without re-encoding (lossless), In my experience not all software or devices can play it
* If you need to transcode into a common format, I can also convert it through ffmpeg, but it may cause a decrease in quality. If necessary, I recommend using professional software to reduce the quality drop.

Please tell me the details of the function you want. :)

感謝您的肯定.
簡短回答 : 是可行的，而且我正面的想整合所有需求的功能
關於這功能能否請您進一步說明.

關於mp4 :
* 是一種封裝格式
* 當選擇格式為mp4+m4a時，可以直接得到mp4檔案
* 我能不轉檔(無損)直接封裝成mp4, 但在我的經驗裡不是所有播放器(裝置)都能播放
* 如果你需要轉檔為標準格式, 我也能透過ffmpeg去處理, 但可能會造成失真, 如果有這需求, 我建議使用專門轉檔的軟體，可以減少品質的下降

還請您說明關於這功能的細節。 :)

**Comment by lovaxi** [comment]
Got it. I made a mistake. 
Tks.
