### ISSUE TITLE
希望可以添加代理设置项

### ISSUE THREAD

**Issue by kongbai39** [kannagi0303/yt-dlp-gui#42]
请求增加http或者socks代理支持

**Comment by kannagi0303** [comment]
您好，这个我可以增加设定选项去实现这项支持。
可以在下次更新时加入此项功能。

如果您急需或是长期使用固定的代理，目前您可以透过设定 [Configuration](https://github.com/kannagi0303/yt-dlp-gui/wiki/Use-Configuration)
新增一个纯文字文件放置在`configs`子资料夹中
```
--proxy socks5://user:pass@127.0.0.1:1080/
```
这样每个下载将会帮你添加此参数
您也可以使用多个文字文件建立您常用的代理
进入到`Options`页面中的`Configuration`将会列出这些文件清单，方便你随时在这些文件设定中切换
当你退出再次执行时，这项目依旧会记忆您上次所选择的文件
详细参数请参考[yt-dlp说明](https://github.com/yt-dlp/yt-dlp#network-options)

备注：如果您使用(启用)aira2下载，我不确定是否会使用代理，这完全取决于yt-dlp

**Comment by kannagi0303** [comment]
@kongbai39 您好

我发布了新的版本，现在可以在 `Options` 设定 `Proxy`
您可以尝试看看，如果遇到有发生问题可以再提出来一同讨论。
希望您能用的愉快。
