### ISSUE TITLE
チャプター分割された動画のダウンロード

### ISSUE THREAD

**Issue by masked-shizuma** [kannagi0303/yt-dlp-gui#44]
お世話になります。
yt-glp-gui (ver:2022.11.14)を使用しています。
動画の中にはチャプター分割されたものがありますが、それをチャプター単位で保存する機能を追加して頂く事は可能でしょうか。
例えば5つのチャプターに分割された動画があったとして、ダウンロードを実行すると5つのファイルとして保存するといった仕組みです。

以上、ご検討宜しくお願い致します。

**Comment by kannagi0303** [comment]
ご利用ありがとうございます～

今のバージョンは
AdvanceタブのTime Rangeにチャプターの名を入力して
単一のチャプターのみをダウンロードするは可能です。

一応yt-dlpのパラメタリストをチェックしました、チャプター分割保存の機能があります。( `--split-chapter` )
guiの方がどんな実現するはまた分からない（GUIの処理手順はyt-dlpと少し違うから）
すいません、実験しないと分からない、時間は掛かります。
実用な機能と思いますから、**必ず**前向きに検討します。

**Comment by masked-shizuma** [comment]
回答有難うございます。

お手数をおかけしますがご検討宜しくお願い致します。

**Comment by kannagi0303** [comment]
@masked-shizuma お疲れ様です。

新たしいのバージョンはリリースした。
チャプター機能は追加しました。
ロスレス分割から、分割されたのチャプターはややズレてるかもしれない（冒頭の部分）
この機能を貴方に満たすことを願っています

また質問や提案があれば、いつでもお待ちしてます。

**Comment by masked-shizuma** [comment]
対応有難うございます。
早速使わせて頂いております。

**Comment by candrapersada** [comment]
how to use split by chapters to download only audio?
