### ISSUE TITLE
Suggestion: Show HDR tag if it is HDR video in video selection list (mp4 or webm)

### ISSUE THREAD

**Issue by icebits** [kannagi0303/yt-dlp-gui#45]
Here the sample HDR www.youtube.com/watch?v=njX2bu-_Vw4

**Comment by kannagi0303** [comment]
Thank you for your suggestion
I have less exposure to HDR video, so I forgot about it.
In the next release, I will give priority to adding this information :)

**Comment by kannagi0303** [comment]
Hello

A new version has been released and Dynamic Range information has been added to the list.
