### ISSUE TITLE
[Feature Request] Auto-select preferred resolution and formats 

### ISSUE THREAD

**Issue by suwagawaki** [kannagi0303/yt-dlp-gui#48]
First of all, I want to thank you for developing this program. It is excellent! Thank you for your continued development, as well. 

One feature I would like to see added in the future is the ability to set preferences. For example, choose 720p@60fps, VP9+OPUS when available. In the event there are several options for the chosen format, choose lowest size. So far, I have only noticed multiple options for audio formats such as OPUS.

**Comment by kannagi0303** [comment]
Thank you for liking this program.

First of all, this setting will not be added at present. The main reason is that there are too many formats of websites and videos, and it is impossible to achieve a simple and clear interface according to the needs of different users.

The highest priority item is relatively okay, but each user will have a second or third priority requirement, so it is difficult to meet every user on the UI.

However, this part allows users to achieve `Auto-select preferred resolution and formats` through Configuration.

You can refer wiki : [Configuration](https://github.com/kannagi0303/yt-dlp-gui/wiki/Use-Configuration)

Then create a text file
````
-f "bv*[ext=webm][height<=720][fps>=59]+ba[ext=webm]/bv*+ba/b"
````
According to the configuration in the wiki, you can achieve the functions you need.

Use this method to better set your priorities, 2nd 3rd.. etc.

Finally, thank you for your support. If you have any questions, please ask again. :)

**Comment by suwagawaki** [comment]
Thanks for the reply, I'll take a look at those configuration options!
