### ISSUE TITLE
[Feature Request] Speed Limit

### ISSUE THREAD

**Issue by Yoksven** [kannagi0303/yt-dlp-gui#49]
Yt-dlp already has that option (-r), so it would be nice to see it in the GUI as well or at least be able to pass extra parameters as a string (in "advance" section for example).

**Comment by kannagi0303** [comment]
Hello, sorry for keeping you waiting! I have added an option in the GUI interface to set the limit-rate. If you are interested, you can try the latest version.

**Comment by Yoksven** [comment]
Thanks. Also "time range" is a very nice feature, thanks for adding it too.
