### ISSUE TITLE
Add a Partial Download input box

### ISSUE THREAD

**Issue by Vespart** [kannagi0303/yt-dlp-gui#5]
Hello!!
First of all **lovely work**, I was tinkering with it and I found that it does the job amazingly, thank you for the GUI!

I was thinking if it would be possible to add a text input box to be able to use the argument `--download-sections` from ty-dlp.
If possible the time range specification that the documentation shows: e.g. `--download-sections "*10:15-15:00"`.
If this box is left empty it would do the regular full video download and ignore such parameters.

It would be very handy for some of my use cases!

Thank you Kannagi!!

**Comment by kannagi0303** [comment]
thanks for liking :)

I will try to test the usage of this argument, and think of a place to put the textbox (or UI)

**Comment by kannagi0303** [comment]
I have released a new version.
Supported `--download-sections`
If you are interested, you can test it :)

**Comment by Vespart** [comment]
It works amazing, thank you for the work!!
