### ISSUE TITLE
no downloads, only the thumbnail jpeg

### ISSUE THREAD

**Issue by msteer22** [kannagi0303/yt-dlp-gui#50]
Hey there, I just wanted to share my experience (Dell XPS 9700 laptop running windows 10)

I downloaded the yt-dlp, ffmpeg and yt-dlp-gui and put all three in the same directory. I then started it, copied a youtube link and clicked on analyze. I then selected "split by chapters" and provided a path to download with the browse button. Did not make any other changes / settings.

I clicked on download and it started - so far so good. The speed was VERY slow, it took 36 min to download 20mb? Anyway after getting the popup that the download is ready I went to the folder and there was only the jpg. not sure what went wrong.

Disregard this in case I screwed up the installation or missed something but I did try to follow the instructions. 

I provided the feedback as I really appreciate the effort you tried even if it did not work for me.

**Comment by kannagi0303** [comment]
Thank you for using

I can't confirm that you are using the GUI correctly.
You can try to use yt-dlp in the command line to test whether it can be downloaded correctly.
First make sure that yt-dlp and ffmpeg can execute normally in your environment.

If the video can be downloaded normally, but the speed is slow, you can use the downloader aria2 to help you increase the download speed.
