### ISSUE TITLE
I tried the tool to download music from youtube.... maybe a feature to consider is providing the option to not download a video at all as I am only interested in the audio files.

### ISSUE THREAD

**Issue by kannagi0303** [kannagi0303/yt-dlp-gui#51]
I tried the tool to download music from youtube.... maybe a feature to consider is providing the option to not download a video at all as I am only interested in the audio files. 

I could not test what the tool downloaded as it did not work for me but even in case I get a separate video and audio file it would be a waste to download the video just to delete it!

_Originally posted by @msteer22 in https://github.com/kannagi0303/yt-dlp-gui/discussions/13#discussioncomment-4624217_

**Comment by kannagi0303** [comment]
Hello

Only audio can be downloaded.
I can only speculate from the information you provided, you may not have set up yt-dlp and ffmpeg correctly
As I replied to you in another issus, you can try to use the command line mode to execute yt-dlp to see if it can run normally.

**Comment by msteer22** [comment]
Hey there,

that was quick… thank you!

I tried yt-dlp using the command prompt and it worked including the split by chapters and the download of the audio files only. At the end trying to get the command line tool to work was not as much work as I thought.

What worked for me was yt-dlp -x --audio-format mp3 --split-chapters -o chapter:%(section_title)s.%(ext)s https://www.youtube.com/watch?v=xxxx

Btw the splitchapters help of yt-dlp mentioned that ffprobe needs to be available, when I tried your tool I only copied ffmpeg as only this file specifically is mentioned in the wiki. Not sure whether this makes any difference.

The download speed with the yt-dlp was 20 mb per second the whole video downloaded in 6 seconds. Not sure why using the GUI is so slow in comparison.

Anyway I think the GUI you build makes it easier for users like me that have an aversion to using the text commands. I like my mouse GUI 😃

Regards,

Martin

Martin Steer
EnaMar GmbH
Hauptstr. 28
D-15806 Zossen

Mobile  +49 151 65 131413
***@***.******@***.***>

Sitz: Zossen. Registergericht: Amtsgericht Potsdam, HRB 28131
Geschäftsführer: Verena Kuhn, Martin Steer

**Comment by kannagi0303** [comment]
Hello

Thank you for providing the parameters and related information.

However, I don't know why the speed is slower, although sometimes it may be limited by youtube.

The GUI I made is only to provide the UI, instead of the user to execute the yt-dlp command line. In theory there should be no difference.

At present, the GUI only provides the chapter function of Video+Audio, download the entire Video or Audio separately,

Referring to your parameters, you should want to separate the Audio with only a single chapter.
I will try to add this part of the function in subsequent versions, and if ffprobe is needed for help, I will also add this description.

P.S. Sorry I edited your message, because it seems to contain your private information, I removed that part, hope you don't mind.

**Comment by kannagi0303** [comment]
Hello, sorry for the wait. 

Now you can directly change the file extension to the format you want when saving audio. 
If you are interested, please try the new version. Thank you.
