### ISSUE TITLE
Add this GUI to the wiki

### ISSUE THREAD

**Issue by stefnotch** [kannagi0303/yt-dlp-gui#55]
I just noticed that this lovely looking GUI is missing from the great list of youtube-dl GUIs: https://www.reddit.com/r/youtubedl/wiki/info-guis/

It could be worthwhile to contact the subreddit's moderators and politely ask them about adding this GUI. :)

**Comment by kannagi0303** [comment]
Dear @stefnotch 

Thank you for your feedback and suggestion. While I personally have not actively sought to promote this project, feel free to share your positive experience with it anywhere you see fit. However, please note that I cannot guarantee immediate attention to this project at all times.

Thanks again for your support.

Best regards,
