### ISSUE TITLE
Clipboard Error

### ISSUE THREAD

**Issue by jhoooooo** [kannagi0303/yt-dlp-gui#58]
![image](https://user-images.githubusercontent.com/65335648/216721660-5f87bdf4-5588-4243-85b9-37e000effe76.png)

Trying to copy url with clipboard monitoring enabled will prompt clipboard error.

Steps to reproduce:

1. Run yt-dlp-gui.exe 
2. Enable clipboard monitoring.
3. Copy any url.
4. Clipboard error will popup (url will be copied but not autopasted to app).
5. Closing the error and copying same url again will not popup the error again (still without the url autopasted to gui).
6. But trying to copy new url will popup the same error again.

---

Version: yt-dlp-gui 2022.11.29
OS:	Microsoft Windows 11 Home	
IOS version:	10.0.22621 Build 22621

**Comment by kannagi0303** [comment]
Thank you for your feedback
This problem tends to happen when the clipboard is occupied by other programs.
Usually the frequency of occurrence will be relatively random, and it is also a more subtle error.
You can try to reduce the number of programs that monitor the clipboard to improve this problem.
In future versions I will try to solve this problem
Thanks

**Comment by kannagi0303** [comment]
I'm sorry for the wait. 

I have released a new version that improves the stability of this part. If you are interested, you can try it out. 

Thank you.
