### ISSUE TITLE
Automatic download

### ISSUE THREAD

**Issue by Plusader** [kannagi0303/yt-dlp-gui#59]
Hi again!
I have my program configured the way it should work. The only thing that bothers me right now is, that I have to manually click the Download-button. Could you add an option to enable the program to download the copied URL automatically (in best case with a in-before check if the file is already there, which would skip the then unnecessary download)?

**Comment by kannagi0303** [comment]
welcome, nice to see you again

Short answer: I'll try to add it when I have time

:)

**Comment by Plusader** [comment]
It seems YouTube has changed something.
Sometimes I have to analyze and download the video multiple times until an output-file is generated.
An AutoDownload-function could try downloading the file in a loop until the file is present in the destination folder.

**Comment by Plusader** [comment]
Regarding my last post (not the auto-download-function in general) a new yt-dl version helps solving this issue.

**Comment by kannagi0303** [comment]
Sorry for the wait, I have released a new version which includes a simple setting that allows the GUI to start downloading immediately after the analysis is completed, and it also applies to clipboard monitoring.

However, I have not extensively tested this feature and I'm not sure if there will be any issues. If you are interested, please try the new version out. Thank you.

**Comment by Plusader** [comment]
Works as intended, thank you!
