### ISSUE TITLE
Add option to download only one stream

### ISSUE THREAD

**Issue by Delphox** [kannagi0303/yt-dlp-gui#6]
Similar how it's possible to only download one stream via commandline (e.g -f 248). Could be either a checkbox next to Audio/Video, or just an option saying None in the quality select dropdown menu.

**Comment by Delphox** [comment]
Oh another thing I'd like to request too (but don't wanna spam issues) is showing the video FPS on the video stream list too, right now there's no way to tell which is 30FPS and which is 60FPS on videos that have both.

Btw loving the app, been waiting for a competent GUI for yt-dlp for a while. 😀

**Comment by kannagi0303** [comment]
First of all thank you for liking this project.
I was waiting for a competent GUI for yt-dlp too.

about download one stream:
I think it can be a little button, like `Subtitle` Combobox's right side.
This should meet your needs.

about stream's frame rate infomation:
Yes, I can add it, The version will be updated in the near future, it will improve. :)

**Comment by kannagi0303** [comment]
I have released a new version.
Supported Single stream download and showing FPS.
If you are interested, you can test it :)

**Comment by Delphox** [comment]
Very good!! Just tested it. Thank you for implementing it!

Another suggestion I'd make is a setting to hide certain streams. Especially AV1. I've noticed AV1 comes as default for some videos, however AV1 still has very low support and would use a lot of CPU.

**Comment by kannagi0303** [comment]
thanks for your test

Regarding the AV1 format, it is definitely a format that will increase its proportion in the future.
High-resolution video, there may be no other options in streams

I will think of a simple way to filter out too many formats. :)
