### ISSUE TITLE
can you add mkv output ,webm not good for other encoder

### ISSUE THREAD

**Issue by godmd5** [kannagi0303/yt-dlp-gui#61]
like cudacoder ,can not add webm input,and MediaInfo_CLI_22.12 can add to tools?

**Comment by kannagi0303** [comment]
Thank you for using.
Regarding the issue in your title, I will add the option for you to manually change the format to save as MKV during the save process. Basically, WebM is an extension of MKV, so other software may also add support in the future.
As for the content of your message, I'm not quite sure what you're trying to express. Could you please provide more information so I can better understand what you want to know?

**Comment by kannagi0303** [comment]
Hello, I have released a new version that may or may not meet your needs. Now, after the analysis is complete, you can click Browse and manually change the file name to .mkv, and the GUI will save it in standard mkv format. Although I haven't thoroughly tested it, if you are interested, you can try the new version.

**Comment by godmd5** [comment]
thank you
