### ISSUE TITLE
Click the analyze button, no response.

### ISSUE THREAD

**Issue by devyujie** [kannagi0303/yt-dlp-gui#64]
It seems to need some updates, there is no way to analyze the video now

**Comment by Plusader** [comment]
You need to download the new version of yt-dl. Worked for me (as it seems right now).

**Comment by yuta1558** [comment]
Surely he is right, it works fine if I keep the original yt-dlp in the same directory.

**Comment by BBChapnick** [comment]
Had the same issue, Plusader's suggestion fixed the issue. (Windows 11) Make sure yt-dlp-gui.exe is in the same directory as yt-dlp  and ffmpeg.exe. As per the Instructions in the wiki under heading: "Use yt-dlp-gui"
 
 yt-dlp-gui Wiki: https://github.com/kannagi0303/yt-dlp-gui/wiki/Getting-Started

**Comment by devyujie** [comment]
Thanks guys, it worked out!
