### ISSUE TITLE
[Feature Request] --embed-thumbnail function

### ISSUE THREAD

**Issue by billyphuse** [kannagi0303/yt-dlp-gui#66]
how to --embed-thumbnail ?

**Comment by kannagi0303** [comment]
Thank you for using my GUI.
Currently, this feature is not supported because my GUI workflow is slightly different from using yt-dlp directly, so it cannot be directly added. I will consider adding this feature later, and I will prioritize it lower on the list.

**Comment by kannagi0303** [comment]
Hello,

I have added this feature in the new version, which has undergone significant changes and may have some rough edges in execution. 

If you're interested, you can try it out and see how it works.

**Comment by kannagi0303** [comment]
Hello,

I have added a feature that allows users to save subtitles in other formats and embed chapter markers within videos or audio. As for the metadata section, I did not receive a more detailed explanation from you, so I'm not sure what your requirements are.

Regarding multiple subtitles and full subtitles, I don't have a better solution at the moment. Please understand.

The new version has undergone significant changes and may have some rough edges. 
If you're interested, you can try it out and see how it works.
