### ISSUE TITLE
yt-dlp-gui软件设置启用aria2c后无法下载youtube视频

### ISSUE THREAD

**Issue by niaoda** [kannagi0303/yt-dlp-gui#67]
### **没有勾选aria2c前：**
可以下载youtube视频 我开启了代理模式我的代理服务器1G带宽但是下载速度很慢

![yt-dlp-gui](https://t2.picb.cc/2023/03/02/IHD2FD.jpg)
![yt-dlp-gui](https://t2.picb.cc/2023/03/02/IHDVVv.jpg)

### **勾选开启aria2c后：**
无法下载youtube视频 点击下载直接弹窗下载完成 其实没有下载内容到本地

![yt-dlp-gui](https://t2.picb.cc/2023/03/02/IHDgGi.jpg)

**yt-dlp-gui软件-设置-启用aria2c 后无法下载youtube视频
点击 下载后会字节弹窗下载已完成，问题是根本没有下载视频
关闭-启用aria2c后能正常下载youtube视频，但是下载速度很慢只有4.55M/s左右
yt-dlp-gui软件我设置了socks5代理下载，我的代理服务器是1G带宽
yt-dlp-gui软件配合yt-dlp.exe下载速度连100兆都达不到
还有一个问题就是软件界面字体显示太小，能否添加一个功能改变字体格式改变字体大小？**

**Comment by niaoda** [comment]
大佬你好，就是无法使用 aria2 下载，勾选开启aria2后无法下载youtube

**Comment by kannagi0303** [comment]
如果您熟悉命令列模式下载的话，我推荐你可以尝试看看。

我猜测是使用aria2c的时候没有设置到proxy。
在命令列模式下可以使用
```
yt-dlp --proxy socks5://127.0.0.1:7890 https://www.youtube.com/watch?v=NqAfZoT62d8 --external-downloader aria2c --external-downloader-args '--all-proxy="socks5://127.0.0.1:7890"'
```
如果能成功的下载，可以设置一个设置文件(Configuration)，在文件中新增一列，并且在设置页选择这个文件
```
--external-downloader-args '--all-proxy="socks5://127.0.0.1:7890"'
```
希望这样能解决下载时遇到的问题。

至于下载速度快慢，您可以透过修改User-Agent的方式，看能不能规避掉有可能的限速，youtube可能有许多方式可以限制特定的下载方式，有些人有提过这问题，但我无法去证实他的正确性，至少我的软件源代码都公开的情况下，我没有去对速度进行任何干涉。希望这能得到您的谅解。

**Comment by niaoda** [comment]
![](https://t2.picb.cc/2023/03/02/IrtbWj.jpg)
谢谢大佬的耐心解答
yt-dlp.exe --proxy http://127.0.0.1:7890/ https://www.youtube.com/watch?v=NqAfZoT62d8 --external-downloader aria2c --external-downloader-args '--all-proxy="http://127.0.0.1:7890"'
用你发给我的命令下载没问题 带宽基本要跑满了下载速度很快
我想用你的软件端 开启 aria2c 功能下载视频 快快快啊 多线程 往大佬修复这个aria2c bug

**Comment by kannagi0303** [comment]
我必须得等到有空闲时间的时候才能修正，在此之前也有许多人的建议与改进要处理。

如果你想现在就直接使用的话，您可以先参考这篇说明

https://github.com/kannagi0303/yt-dlp-gui/wiki/Use-Configuration

把文字文件的內容改成
```
--external-downloader-args '--all-proxy="socks5://127.0.0.1:7890"'
```
这个设置文件的目的是将每次下载都加入这行参数
重新启动软件，再把设置切换到该文字文件名称，这样应该就能用了

**Comment by niaoda** [comment]
我已经了解
谢谢你的耐心解答打扰了。

**Comment by kannagi0303** [comment]
您好，我发布了新的版本，现在会自动套用proxy的设定到aria2上面。

由于我这边没有跟您相同的环境，不确定您在使用时会不会遇到问题，如果您有兴趣可以试一下新版本。

感谢您的使用。

**Comment by niaoda** [comment]
> 您好，我发布了新的版本，现在会自动套用proxy的设定到aria2上面。
> 
> 由于我这边没有跟您相同的环境，不确定您在使用时会不会遇到问题，如果您有兴趣可以试一下新版本。
> 
> 感谢您的使用。

好的乐意测试，请稍等！

**Comment by niaoda** [comment]
软件开启 aria2c 还是无法下载 youtube视频
直接弹窗已经下载完成，其实根本没有下载到视频
![](https://t2.picb.cc/2023/03/05/I5xSha.jpg)

软件关闭 aria2c 可以下载 youtube视频 
但是代理依然没有效果。说明代理没有启用
![](https://t2.picb.cc/2023/03/05/I5x0ed.jpg)

**Comment by kannagi0303** [comment]
感谢您迅速的回应并且作了测试。

我做了一点小小的修改，希望这次能正常执行。
由于只是小更动，我没有推进版本号，如果方便麻烦您再下载一次最终版本即可。

**Comment by niaoda** [comment]
> 感谢您迅速的回应并且作了测试。
> 
> 我做了一点小小的修改，希望这次能正常执行。 由于只是小更动，我没有推进版本号，如果方便麻烦您再下载一次最终版本即可。


**你好，我重新下载了你刚才上传的软件。还是和你小小的修改之前的那个版本一个的问题。

开启 代理还是不管用 速度还是4.5M/s 没效果
开启 aria2c 还是无法下载 youtube视频**

**Comment by kannagi0303** [comment]
好的，我会多花点时间看能不能模拟出您那边的环境来测试，感谢您的回复。

**Comment by niaoda** [comment]
> 好的，我会多花点时间看能不能模拟出您那边的环境来测试，感谢您的回复。

你好，我是Windows11系统

版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎8/‎11
操作系统版本	22624.1391
体验	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by kannagi0303** [comment]
我想可能主要是您有使用VPN的关系，我这边的用户比较少，而且大概都没使用代理，所以在您之前都没有用户反映过。

还是感谢您的耐心，麻烦您再等段时间

**Comment by niaoda** [comment]
> 

好的谢谢！
不过直接用 yt-dlp.exe 可以使用代理。
用yt-dlp-gui.exe 代理就不起作用。

**Comment by niaoda** [comment]
> 我想可能主要是您有使用VPN的关系，我这边的用户比较少，而且大概都没使用代理，所以在您之前都没有用户反映过。
> 
> 还是感谢您的耐心，麻烦您再等段时间

![](https://t2.picb.cc/2023/03/05/I5xFwD.jpg)

你好 windows11 不能使用代理下载的原因找到了
代理格式不是：socks5://
代理格式是：http://
请看上面图 我自定义格式代理格式为：http://127.0.0.1:7890 正常下载了。
--external-downloader-args '--all-proxy="http://127.0.0.1:7890"'

**Comment by niaoda** [comment]
> > 我想可能主要是您有使用VPN的关系，我这边的用户比较少，而且大概都没使用代理，所以在您之前都没有用户反映过。
> > 还是感谢您的耐心，麻烦您再等段时间
> 
> ![](https://camo.githubusercontent.com/256401422b29563a4fbcdc8f3a0d977a966ac316fc07584eb3eaf30421071581/68747470733a2f2f74322e706963622e63632f323032332f30332f30352f4935784677442e6a7067)
> 
> 你好 windows11 不能使用代理下载的原因找到了 代理格式不是：socks5:// 代理格式是：http:// 请看上面图 我自定义代理格式为：http://127.0.0.1:7890 正常下载了。 --external-downloader-args '--all-proxy="http://127.0.0.1:7890"'

大佬软件上面的 下载略缩图  勾选后也无法下载略缩图。

**Comment by kannagi0303** [comment]
这个我会再修正过，不一定会在下一版中改正，还有些用户需求排着，麻烦您再耐心等等。

**Comment by kannagi0303** [comment]
我把下载缩图的部份改过了，现在应该可以套用proxy设定，我没有详细查阅过还有哪边有相关的问题，您可以使用看看，如果还有问题在麻烦您回报回来，感谢您所有付出的时间与精力。

**Comment by niaoda** [comment]
![yt-dlp-gui 2023.03.08](https://t2.picb.cc/2023/03/08/IAelDL.jpg)
![yt-dlp-gui 2023.03.08](https://t2.picb.cc/2023/03/08/IAeCnW.jpg)
![yt-dlp-gui 2023.03.08](https://t2.picb.cc/2023/03/08/IAec7w.jpg)
**新版yt-dlp-gui 2023.03.08，之前反应的问题都解决修复了 大佬辛苦了！**

**Comment by niaoda** [comment]
![yt-dlp-gui](https://t2.picb.cc/2023/03/10/IAPq38.jpg)

**大佬 你好，
使用最新版 yt-dlp.exe 2023.03.04 下载youtube会有问题
yt-dlp-gui 的软件界面UI“视频”绿色进度条不显示下载进度
而且指定下载视频文件夹，会缓存一堆下载的临时文件。
但是缓存的文件最后能正常合并 并自己删除临时文件，保留合并好的文件。

主要问题bug是：yt-dlp-gui 的软件界面UI“视频”那个绿色进度条 不显示下载进度**

**Comment by kannagi0303** [comment]
关于您的问题，首先是参考 #3、#24。
这进度条主要是依赖于yt-dlp或是aria2所提供的资讯，有些情况下这些依赖的工具并不会提共资讯，所以绿色进度条没反应是有可能的，尤其是直播类的就完全不会有进度。

至于速度不准确的部分，这速度也是yt-dlp与aria2所提供的，每个工具所提供的参考值都会有不同的公式但目的大多是尽可能贴近理想的预测速度，包含您在系统列的工具也是有自己的计算方法，以我个人的经验而言，这些数值都是正确的。

比如说下载一个档案，第一秒速度是10M，第二秒是10M，第三秒是0M
对于A工具来说可能每三秒取样一次，它就给你6.6M的数字。
对于B工具来说可能每一秒取样一次，它就会在第三秒的时候给你0M的数字。

关于您提到会缓存一堆文件，这是正常的，请参考 [Release 2023.03.08](https://github.com/kannagi0303/yt-dlp-gui/releases/tag/2023.03.08) 的Changelog，原本这些缓存会放在yt-dlp-gui的所在资料夹中，我修改了预设为储存目的地的资料夹中，当然，新版本我也提供了设置，可以让你放在不同位置，这些缓存都是有必要的。

希望以上有解答您的问题，如果可以的话，可以将不同的问题重新开个issue题目，除了比较不会让我忽略掉已经Close的项目之外，这些问答也可以让遇到相同问题的使用者方便找到解答，希望您能谅解，谢谢。
