### ISSUE TITLE
Ver 2023.03.05 is not displaying Japanese

### ISSUE THREAD

**Issue by maboroshin** [kannagi0303/yt-dlp-gui#69]
Ver 2023.03.05 is not showing Japanese translation, UI is still in English.

**Comment by kannagi0303** [comment]
わかりました、問題点を調べてみます。返信ありがとうございます！

Okay, I will investigate the issue. Thank you for your response!

**Comment by kannagi0303** [comment]
改めてありがとうございます、提供いただいたlangをテストし、チェックしました。

提供いただいたlangファイルを使用したところ、最新バージョンと旧バージョンの両方で日本語を表示できないことがわかりました。YAMLファイルの形式を確認すると、20行目に全角スペースが余分に含まれていることがわかりました：
```SubtitleNone: "[なし]"　```
これがプログラムが日本語を解析できない原因となっています。YAMLは比較的友好的でシンプルな形式ですが、この場合は問題が発生しました。ご不便をおかけして申し訳ありません。修正されたファイルを提出していただくか、私が必要な修正を行うこともできます。
<hr/>
Hello, I have tested and checked the lang file you provided.

I used the lang file you provided and found that I couldn't display Japanese characters in both the latest and older versions. I checked the format of the yaml file and found that there is an extra full-width space at the end of line 20:
```SubtitleNone: "[なし]"　```
This is causing the program to fail to parse the Japanese characters. Although YAML is a relatively friendly and simple format, it caused trouble in this case. I apologize for any inconvenience this may have caused. If you would like, you can submit a corrected file, or I can make the necessary changes from my end.

**Comment by maboroshin** [comment]
ごめんなさい。私の入力ミスのようですね。
カンナギさんが修正してください。お願いします。

**Comment by kannagi0303** [comment]
ご心配なく、日本語を提供することに応じていただき、ありがとうございます。私の母語は日本語ではありませんので、地元の方々に協力していただくことで、より正確で適切な翻訳を提供できることを感謝しています。今後とも、いろいろな面でご指導いただけると幸いです。

**Comment by maboroshin** [comment]
@kannagi0303
Ver 2023.03.08 でも英語です。日本語翻訳は表示されません。

**Comment by kannagi0303** [comment]
![1678339144822](https://user-images.githubusercontent.com/78738403/223927591-35c175f5-b7d5-4284-9c06-63e448ee7fa0.jpg)
こっちは大丈夫けど…　もう一度languagesからダウンロード試し見て？

**Comment by maboroshin** [comment]
できました！ありがとう。

「言語を現地語にする」を見ていなかったです。
https://github.com/kannagi0303/yt-dlp-gui/wiki/Localized-Language
