### ISSUE TITLE
The option and the video extension after downloading are not consistent.

### ISSUE THREAD

**Issue by devyujie** [kannagi0303/yt-dlp-gui#81]
![image](https://user-images.githubusercontent.com/48620527/224685341-3e2599d8-b0fa-42e5-8a9f-6a82a22a7918.png)

**Comment by kannagi0303** [comment]
fixed.

我发布了新版本有对这部分进行加强，然而这版本变动较大，有兴趣可以尝试看看新版本，谢谢。
