### ISSUE TITLE
Update of the French translation

### ISSUE THREAD

**Issue by fds39** [kannagi0303/yt-dlp-gui#87]
Hi, I tried to update the French translation but something is wrong because it stays with the English version.
[french trad.txt](https://github.com/kannagi0303/yt-dlp-gui/files/11019416/french.trad.txt)

**Comment by kannagi0303** [comment]
Line 64:
Aria2

keep two space at start. 
[YAML Lint](https://www.yamllint.com/) can easy to check.

**Comment by kannagi0303** [comment]
I have already fixed it and uploaded it to GitHub. Thank you for your help.

**Comment by fds39** [comment]
Hi, one or two minor French translation changes for a future update.
[yt-dlp-gui_lang.zip](https://github.com/user-attachments/files/17328466/yt-dlp-gui_lang.zip)

By the way, I suggest you add a sample template for conversion to mp3, as so many old players only support this audio format. My wife is a teacher and knows nothing about yt-dlp synthaxis but needs your tool for her classroom. 

This basic .txt file would allow on-the-fly mp3 conversion with yt-dlp GUI:

```
# Convert video files to audio-only files
-x

# Format to convert the audio
--audio-format mp3

# Specify best ffmpeg audio quality to use when converting the audio
--audio-quality 0
```
