### ISSUE TITLE
Maybe there should be the feature to record live streams

### ISSUE THREAD

**Issue by ShiSheng233** [kannagi0303/yt-dlp-gui#9]
Hi!

It's a new feature request.
I think yt-dlp-gui needs to be adapted for downloading live streams.

The adaptations I can think of so far are:
  1. Recognize that the link refers to a live stream but not a video
  2. Automatically detect the start of a live stream and record it

This could be a long-term goal rather than something that needs to be done right now.

Appreciate your work, and hope I can help.

**Comment by kannagi0303** [comment]
Yes, about the new features you requested This is also one of the features I wanted to implement in the first place

But this is a cumbersome feature
Recording live stream directly from the current point in time is the most straightforward. (I can finish it early)

For live broadcast with DVR enabled, there must be a function to start recording from the beginning (or a specific starting point), and live waiting feature for not yet started!

I need to know more about the operation process and features of yt-dlp

If more people can provide the usage of relevant parameters, it can help me to complete this feature better. :)
