### ISSUE TITLE
translation to Spanish- traducción al español

### ISSUE THREAD

**Issue by marcosSea** [kannagi0303/yt-dlp-gui#95]
Hola amigo aqui te paso la traducción al español completo, por que no pude crearlo en pull request jeje soy algo nuevo por acá, pero aquí esta amigo.

Espero que tengas excelente dia amigo y haces un excelente trabajo y pues ya puedes cerrar esta publicacion, porque era para para pasarte la traducción al español😄✌️

[yt-dlp-gui.txt](https://github.com/kannagi0303/yt-dlp-gui/files/11057058/yt-dlp-gui.txt)

**Comment by kannagi0303** [comment]
Hola, gracias por proporcionar la traducción. 

La he colocado en [languages/es-ES](https://github.com/kannagi0303/yt-dlp-gui/blob/master/languages/es-ES/yt-dlp-gui.lang). Por favor, no dudes en contactarme si hay algún problema. :)
